// This file provides the ExternalBlob class, createActor factory, and re-exports
// from backend.d.ts. In a deployed Caffeine project this file is generated by
// @caffeinelabs/bindgen and should not be modified.

import { Actor } from "@icp-sdk/core/agent";
import type { ActorConfig, HttpAgent, Identity } from "@icp-sdk/core/agent";
import { idlFactory } from "./declarations/backend.did";
import type { _SERVICE } from "./declarations/backend.did.d";
import type { backendInterface as _backendInterface } from "./backend.d";

export type { FileRecord, UserProfile, UserRole } from "./backend.d";

// Extend backendInterface to include internal Caffeine methods
export interface backendInterface extends _backendInterface {
  _initializeAccessControlWithSecret(secret: string): Promise<void>;
}

export interface CreateActorOptions {
  agentOptions?: {
    identity?: Identity | Promise<Identity>;
    host?: string;
  };
  agent?: HttpAgent;
  processError?: (e: unknown) => never;
}

/**
 * ExternalBlob represents a file blob that can be uploaded to or downloaded
 * from the Caffeine blob storage gateway.
 */
export class ExternalBlob {
  private _bytes: Uint8Array | null = null;
  private _url: string | null = null;
  onProgress: ((pct: number) => void) | undefined = undefined;

  private constructor() {}

  static fromBytes(bytes: Uint8Array): ExternalBlob {
    const b = new ExternalBlob();
    b._bytes = bytes;
    return b;
  }

  static fromURL(url: string): ExternalBlob {
    const b = new ExternalBlob();
    b._url = url;
    return b;
  }

  withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
    const copy = new ExternalBlob();
    copy._bytes = this._bytes;
    copy._url = this._url;
    copy.onProgress = onProgress;
    return copy;
  }

  async getBytes(): Promise<Uint8Array> {
    if (this._bytes) return this._bytes;
    if (this._url) {
      const res = await fetch(this._url);
      const buf = await res.arrayBuffer();
      this._bytes = new Uint8Array(buf);
      return this._bytes;
    }
    throw new Error("ExternalBlob has no bytes or URL");
  }

  getDirectURL(): string {
    if (this._url) return this._url;
    return "";
  }
}

type RawActor = _SERVICE;

function toNullable<T>(value: [] | [T]): T | null {
  return value.length > 0 ? (value[0] as T) : null;
}

export async function createActor(
  canisterId: string,
  _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>,
  _downloadFile: (bytes: Uint8Array) => Promise<ExternalBlob>,
  options?: CreateActorOptions,
): Promise<backendInterface> {
  const config: ActorConfig = {
    canisterId,
    agent: options?.agent,
  };

  const raw = Actor.createActor<RawActor>(idlFactory, config);

  const processErr = options?.processError ?? ((e: unknown) => { throw e; });

  const wrap = <T>(fn: () => Promise<T>): Promise<T> => {
    return fn().catch(processErr as (e: unknown) => never);
  };

  return {
    async _initializeAccessControlWithSecret(secret: string) {
      return wrap(() => raw._initializeAccessControlWithSecret(secret));
    },
    async assignCallerUserRole(user, role) {
      const variant = { [role]: null } as unknown as Parameters<RawActor["assignCallerUserRole"]>[1];
      return wrap(() => raw.assignCallerUserRole(user, variant));
    },
    async deleteFile(fileId) {
      return wrap(() => raw.deleteFile(fileId));
    },
    async getAllFiles() {
      return wrap(() => raw.getAllFiles());
    },
    async getCallerUserProfile() {
      return wrap(async () => toNullable(await raw.getCallerUserProfile()));
    },
    async getCallerUserRole() {
      const r = await wrap(() => raw.getCallerUserRole());
      const key = Object.keys(r)[0] as "admin" | "user" | "guest";
      return key as unknown as Awaited<ReturnType<_backendInterface["getCallerUserRole"]>>;
    },
    async getFileMetadata(fileId) {
      return wrap(() => raw.getFileMetadata(fileId));
    },
    async getMyFiles() {
      return wrap(() => raw.getMyFiles());
    },
    async getRemainingStorageCapacity() {
      return wrap(() => raw.getRemainingStorageCapacity());
    },
    async getTotalStorageUsed() {
      return wrap(() => raw.getTotalStorageUsed());
    },
    async getUserProfile(user) {
      return wrap(async () => toNullable(await raw.getUserProfile(user)));
    },
    async isCallerAdmin() {
      return wrap(() => raw.isCallerAdmin());
    },
    async saveCallerUserProfile(profile) {
      return wrap(() => raw.saveCallerUserProfile(profile));
    },
    async uploadFile(id, name, size, mimeType, blobId) {
      return wrap(() => raw.uploadFile(id, name, size, mimeType, blobId));
    },
  };
}
